services:
  # 1. Ваше Spring Boot приложение ReBattery
  app:
    build: . # Dockerfile будет лежать в корне проекта, сборка локальная!
    image: rebattery-app
    container_name: rebattery-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # Приложение запустится ТОЛЬКО после полной готовности БД
    environment:
      - TZ=Europe/Moscow
      - JAVA_OPTS=-Duser.timezone=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rebattery_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret_password

  # 2. База данных PostgreSQL (с рабочим зеркалом)
  db:
    # Заменяем на стабильное Docker-зеркало, чтобы обойти блокировку Docker Hub
    image: mirror.gcr.io/library/postgres:16.1-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=rebattery_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: